# Generated by Django 3.2.5 on 2021-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_neighbourhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
