# Generated by Django 3.2.5 on 2021-07-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_profile_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
